/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import javax.swing.ImageIcon;

/**
 *
 * @author LENOVO
 */
public class PhimForm1 extends javax.swing.JPanel {

    /**
     * Creates new form PhimForm
     */
    public PhimForm1() { 
       
        initComponents();
         loadMovies();
    }
private void loadMovies() {
    phim1.MovieCard("Địa Đạo", new ImageIcon(getClass().getResource("/image/godzilla.jpg")),
            new String[]{"10:00", "13:30", "17:00"});
    phim2.MovieCard("Địa Đạo", new ImageIcon(getClass().getResource("/image/diadao.jpg")),
            new String[]{"09:00", "14:00", "20:00"});
    phim3.MovieCard("Địa Đạo", new ImageIcon(getClass().getResource("/image/godzilla.jpg")),
            new String[]{"11:00", "15:30", "19:00"});
    phim4.MovieCard("Địa Đạo", new ImageIcon(getClass().getResource("/image/diadao.jpg")),
            new String[]{"10:30", "13:00","19:00","21:00"});
    phim5.MovieCard("Địa Đạo", new ImageIcon(getClass().getResource("/image/diadao.jpg")),
            new String[]{"12:00", "16:30", "21:00"});
    phim6.MovieCard("Địa Đạo", new ImageIcon(getClass().getResource("/image/diadao.jpg")),
            new String[]{"09:30", "14:30", "20:30"});
    phim7.MovieCard("Địa Đạo", new ImageIcon(getClass().getResource("/image/diadao.jpg")),
            new String[]{"12:00", "16:30", "21:00"});
    phim8.MovieCard("Địa Đạo", new ImageIcon(getClass().getResource("/image/diadao.jpg")),
            new String[]{"09:30", "14:30", "20:30"});
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        phim7 = new component.Phim1();
        phim5 = new component.Phim1();
        phim6 = new component.Phim1();
        phim1 = new component.Phim1();
        phim8 = new component.Phim1();
        phim2 = new component.Phim1();
        phim3 = new component.Phim1();
        phim4 = new component.Phim1();
        jLabel1 = new javax.swing.JLabel();

        jPanel2.setLayout(new java.awt.GridLayout(2, 4));
        jPanel2.add(phim7);
        jPanel2.add(phim5);
        jPanel2.add(phim6);
        jPanel2.add(phim1);
        jPanel2.add(phim8);
        jPanel2.add(phim2);
        jPanel2.add(phim3);
        jPanel2.add(phim4);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN LỊCH CHIẾU");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleParent(jLabel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private component.Phim1 phim1;
    private component.Phim1 phim2;
    private component.Phim1 phim3;
    private component.Phim1 phim4;
    private component.Phim1 phim5;
    private component.Phim1 phim6;
    private component.Phim1 phim7;
    private component.Phim1 phim8;
    // End of variables declaration//GEN-END:variables
}
